name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # позволяет запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Expo
        run: npm install -g expo-cli eas-cli
      
      - name: Install dependencies
        run: npm install
      
      - name: Create .env file
        run: |
          echo "EXPO_PUBLIC_ADMOB_APP_ID_ANDROID=${{ secrets.EXPO_PUBLIC_ADMOB_APP_ID_ANDROID }}" >> .env
          echo "EXPO_PUBLIC_ADMOB_REWARDED_ANDROID_ID=${{ secrets.EXPO_PUBLIC_ADMOB_REWARDED_ANDROID_ID }}" >> .env
          echo "EXPO_PUBLIC_ADMOB_INTERSTITIAL_ANDROID_ID=${{ secrets.EXPO_PUBLIC_ADMOB_INTERSTITIAL_ANDROID_ID }}" >> .env
      
      - name: Build APK
        run: |
          cd coupon-app
          eas build --platform android --profile development --non-interactive --output=./app.apk
      
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: coupon-app/app.apk
